language: minimal

services:
  - docker

env:
  - TARGET=base
  - TARGET=latest
  - TARGET=gui
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make ${TARGET}
