name: Build and push docker images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  OCTAVE_VERSION: 6.4.0
  DEBIAN_VERSION: 12.1

jobs:
  build-and-push:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        image_version: ['debian', 'gui']
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v4

      - name: Login to Docker
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

      - name: Build image for ${{matrix.image_version}}
        id: build_image
        run: |
          docker build \
          --build-arg "OCTAVE_VERSION=${OCTAVE_VERSION}" \
          --build-arg "DEBIAN_VERSION=${DEBIAN_VERSION}" \
          -f Dockerfile.${{matrix.image_version}} \
          -t ${DOCKER_USER}/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}-$GITHUB_SHA \
          .
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag image with git SHA and latest
        run: |
          docker tag $DOCKER_USER/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}-$GITHUB_SHA $DOCKER_USER/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}-latest
          docker tag $DOCKER_USER/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}-$GITHUB_SHA $DOCKER_USER/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule') && github.ref_protected }}
        run: |
          docker push $DOCKER_USER/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}-$GITHUB_SHA
          docker push $DOCKER_USER/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}-latest
          docker push $DOCKER_USER/$REPO_NAME:${{matrix.image_version}}-${OCTAVE_VERSION}
